### PR TITLE
feat: add tpm plugin

### LINKED ISSUE #93: Request to use a fork of vim-tmux-navigator tpm with resize support
Hello!

Have you considered forking vim-tmux-navigator (the tmux config, not the vim plugin) so that we could push the resize config into that repo? Main motivation is I'd rather have the tmux conf snippet for resizing moved into the tpm plugin, rather than copy pasting it into my own (and everyone else's) tmux.conf.

I could create the tpm plugin for myself, but I think it'd be beneficial for everyone to be able to do just:
```tmux
set -g @plugin 'aserowy/tmux.nvim'
```

I can submit a PR if you'r open to it.
Thanks!

### PR DESCRIPTION
**Pull request by joeveiga**
Close #93

### CODE REVIEW

**Comment by aserowy** [comment]
Tyvm ❤️

**Review by aserowy — APPROVED** [review]

**Comment by aserowy** [comment]
@joeveiga can you please review the linter findings?

**Review by aserowy — APPROVED** [review]

**Comment by joeveiga** [comment]
> @joeveiga can you please review the linter findings?

@aserowy I fixed the most straightforward ones but my bash scripting is very limited :). I copy pasted most of that from the readme. If you can take a look it'd be appreciated.

**Comment by aserowy** [comment]
@joeveiga

heho, finally got time to look into the styling. Can you please check if everything works as expected aswell? (i checked it myself, but four eyes :D...)

Kind regards and ty for your work!
Alexander

**Comment by joeveiga** [comment]
Hey @aserowy! Thanks for taking a look! So I tested it an it seems to work fine. However, disabling cycle navigation doesn't seem to work (`set -g @tmux-nvim-navigation-cycle false`). I tried using the snippet and it also doesn't work for me so maybe not related to these changes. Does it work for you? Maybe it is something in my setup 🤷

**Comment by aserowy** [comment]
hmmm, this worked for me. Thus, ill merge it and when it fails for others as well, we can open a ticket to track the issue.

**Comment by joeveiga** [comment]
> hmmm, this worked for me. Thus, ill merge it and when it fails for others as well, we can open a ticket to track the issue.

Sounds like a plan! TY!

**Pull request merged**
